### ISSUE TITLE
open_now and utc_offset is deprecated as of November 2019.

### ISSUE THREAD

**Issue by amirulabu** [frandiox/vue-geo-suggest#6]
![Screenshot 2020-10-20 at 12 39 47 PM](https://user-images.githubusercontent.com/10055534/96540958-8f811b80-12d1-11eb-8249-144af43f37ed.png)

screenshot is showing the console section in browser dev tools

**Comment by frandiox** [comment]
@amirulabu Thanks for informing about this!

However, I don't think we need to update anything in this library since we don't use the deprecated fields directly.
I guess the places library is automatically showing these warnings/errors when the `getDetails()` method is called so there's nothing we can do to hide them.

I'm closing this since there's nothing to do but please feel free to open it if I missed anything.
